# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-03 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('1', 'Study'), ('2', 'Job')], max_length=50)),
                ('education', models.CharField(blank=True, choices=[('PG', 'PG'), ('DIPLOMA', 'DIPLOMA'), ('UG', 'UG')], max_length=50, null=True)),
                ('instituition', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_stay', models.CharField(blank=True, max_length=50, null=True)),
                ('stay_status', models.CharField(blank=True, choices=[('1', 'KERALA'), ('2', 'Out of kerala'), ('3', 'Out of India')], max_length=50, null=True)),
                ('home_hostel', models.CharField(blank=True, choices=[('1', 'Home'), ('2', 'Hostel')], max_length=50, null=True)),
                ('availability', models.CharField(blank=True, choices=[('1', 'once in a year'), ('2', 'Once in a month'), ('3', 'Once in a week')], max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('job', models.ManyToManyField(blank=True, null=True, to='youth.Profession')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouthDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('married', models.CharField(choices=[('yes', 'Yes'), ('No', 'No')], max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youth.Region')),
                ('blood_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youth.BloodGroup')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youth.Ward')),
            ],
        ),
        migrations.CreateModel(
            name='YouthFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('father_job', models.ManyToManyField(blank=True, null=True, related_name='father_profession', to='youth.Profession')),
                ('mother_job', models.ManyToManyField(blank=True, null=True, related_name='mother_profession', to='youth.Profession')),
                ('youth_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youth.YouthDetails')),
            ],
        ),
        migrations.AddField(
            model_name='professionaldetails',
            name='youth_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youth.YouthDetails'),
        ),
    ]
