# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-04 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionaldetails',
            name='job',
        ),
        migrations.RemoveField(
            model_name='professionaldetails',
            name='youth_detail',
        ),
        migrations.RemoveField(
            model_name='youthfamily',
            name='father_job',
        ),
        migrations.RemoveField(
            model_name='youthfamily',
            name='mother_job',
        ),
        migrations.RemoveField(
            model_name='youthfamily',
            name='youth_detail',
        ),
        migrations.AddField(
            model_name='youthdetails',
            name='availability',
            field=models.CharField(blank=True, choices=[('1', 'once in a year'), ('2', 'Once in a month'), ('3', 'Once in a week')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='youthdetails',
            name='education',
            field=models.CharField(blank=True, choices=[('PG', 'PG'), ('DIPLOMA', 'DIPLOMA'), ('UG', 'UG')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='youthdetails',
            name='father_job',
            field=models.ManyToManyField(blank=True, null=True, related_name='father_profession', to='youth.Profession'),
        ),
        migrations.AddField(
            model_name='youthdetails',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='youthdetails',
            name='home_hostel',
            field=models.CharField(blank=True, choices=[('1', 'Home'), ('2', 'Hostel')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='youthdetails',
            name='house_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youthdetails',
            name='instituition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='youthdetails',
            name='job',
            field=models.ManyToManyField(blank=True, null=True, to='youth.Profession'),
        ),
        migrations.AddField(
            model_name='youthdetails',
            name='mother_job',
            field=models.ManyToManyField(blank=True, null=True, related_name='mother_profession', to='youth.Profession'),
        ),
        migrations.AddField(
            model_name='youthdetails',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='youthdetails',
            name='place_of_stay',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='youthdetails',
            name='profession',
            field=models.CharField(choices=[('1', 'Study'), ('2', 'Job')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youthdetails',
            name='stay_status',
            field=models.CharField(blank=True, choices=[('1', 'KERALA'), ('2', 'Out of kerala'), ('3', 'Out of India')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ProfessionalDetails',
        ),
        migrations.DeleteModel(
            name='YouthFamily',
        ),
    ]
